### PR TITLE
DVX-11943: change faraday version restriction

### PR DESCRIPTION
**Pull request by agustibr**

### CODE REVIEW

**Comment by ozgun** [comment]
+1 Looks good, thanks!

**Comment by agustibr** [comment]
Source branch needs to be changed to `tag/v0.11.1`

**Comment by dsager** [comment]
+1

**Comment by agustibr** [comment]
Changed source branch, no conflicts (since master is the latest version of the gem)

**Comment by agustibr** [comment]
Thanks!

**Pull request merged**
