### PR TITLE
Add Request Campaign to Mrkt Marketo Gem

### PR DESCRIPTION
**Pull request by nicolas-fricke**
This adds the functionality to request a Smart Campaign for certain leads to our forked Gem "Mrkt" which we will from now on use to make REST requests to Marketo. We need the Smart Campaign feature to trigger emails.

### CODE REVIEW

**Comment by christofdamian** [comment]
+1

**Comment by dsager** [comment]
+1
nice. are we making a PR to the official repo?

**Comment by nicolas-fricke** [comment]
That's the plan :) @christofdamian – Is Marvin already active in this repo and will eventually merge this PR or do we have to do that manually?

**Comment by christofdamian** [comment]
should happen soonish

**Comment by christofdamian** [comment]
poor marvin didn't have access :-)

**Comment by nicolas-fricke** [comment]
Thanks :)

**Comment by nicolas-fricke** [comment]
Opened a PR to the original repo: https://github.com/raszi/mrkt/pull/4

**Pull request merged**
